### ISSUE TITLE
TEST 02 - BUG API

### ISSUE THREAD

**Issue by HieuQB** [HieuQB/yummy_server#2]
- [x] Create Meeting

- [x] List Post

- [x] Git list Usernear và List user tìm kiếm được thì nên loại User đang đăng nhập ra

- [x] API update password 

- [x] RealServerRoutes -> SetNotiMeeting -> chưa test trên giao diện được -> Chưa chụp được

- [x] Gửi noti gợi ý bài viết nên loại trừ user đang đăng nhập ra (kiểm tra luôn các api noti khác)

**Comment by vthhanh96** [comment]
- [ ]  Update bài viết bị lỗi
<img width="1089" alt="screen shot 2018-12-22 at 7 33 25 am" src="https://user-images.githubusercontent.com/19782537/50368512-078a3780-05bc-11e9-8940-a6a3b1ba3d0d.png">

- [ ]  Xoá comment trong bài post bị lỗi (nhưng mà lần đầu xoá được)
<img width="1078" alt="screen shot 2018-12-22 at 7 52 45 am" src="https://user-images.githubusercontent.com/19782537/50368752-b891d180-05be-11e9-84c5-4f4be1d96845.png">

- [ ]  Update bình luận của bản thân không được, cứ báo là không có permission
<img width="1079" alt="screen shot 2018-12-22 at 7 59 02 am" src="https://user-images.githubusercontent.com/19782537/50368861-8df44880-05bf-11e9-8df3-452e88673549.png">

**Comment by vthhanh96** [comment]
- [ ]  Tạo api check xem 1 người có quyền đánh giá những người tham gia một meeting hay không?
params truyền lên: meeting_id
