### ISSUE TITLE
TEST 03: BUG PHÁT SINH THÊM

### ISSUE THREAD

**Issue by HieuQB** [HieuQB/yummy_server#3]
- [x] Nhận lời mời đi ăn cùng (Hiện popup dạng invite) rồi nhấn nút ĐỒng Ý --> Báo lỗi Unknow Error và Thất bại ?

- [x] Crash app và Không thể vào màn hình CHỈNH SỬA BÀI VIẾT

- [x] Đăng nhập bằng nick hieu@gmail.com --> Vào màn hình list Thông báo (đi từ menu chính) --> Không hiển thị được danh sách (Test trên Postman thì thấy có data)

- [x] Hiện tại đang bị Crash app khi nhấn vào icon đính kèm link ở trang Tạo bài viết

- [x] Nên check không cho bình luận nếu như bình luận rỗng

- [x] Khi quay lại màn hình trang chủ nên tự động load lại trang. Hiện tại phải load thủ công mới đúng data mới nhất

- [x] Ở Danh sách người gần đây ngoài trang chủ, thiết nghĩ nên hiển thị là đang online hay offline (server đã trả về biến isOnline) và nên hiển thị thêm trường khoảng cách nữa

- [x] Vẫn chưa thấy hiển thị thành công content post??

- [x] Làm sao cho có thể rating meeting bất kì lúc nào chứ k phải đợi server yêu cầu mới rating

- [x] Không thể cập nhật ảnh đại diện trong CHỈNH SỬA PROFILE (à text style của Ngày sinh và Địa chỉ hiện tại đang bị mờ) và Cập nhật địa chỉ chỉ cập nhật text chứ chưa cập nhật tọa độ coordinates

- [x] Tạo bài post -> chọn đính kèm link -> Nhập mp3.com.vn -> xong nó không làm gì hết

- [x] Title nên thuần Viêt: Nhập Link, Chỉnh Sửa Profile

- [x] Không hiển thị hình của bài Post đc

- [x] Nên check not null với một số trường khi tạo bài viết mới (hiện tại không nhập gì vẫn cho tạo)

- [x] Lúc chọn ngày nên chặn không cho chọn những ngày đã qua (nên lớn hơn ngày hiện tại)

**Comment by vthhanh96** [comment]
> Ở Danh sách người gần đây ngoài trang chủ, thiết nghĩ nên hiển thị là đang online hay offline (server đã trả về biến isOnline) và nên hiển thị thêm trường khoảng cách nữa
Đã có chức năng hiển thị online offline rồi. Còn khoảng cách thì ko tính được, hiện tại cũng ko parse được dạng dữ liệu khoảng cách

**Comment by vthhanh96** [comment]
> Đăng nhập bằng nick hieu@gmail.com --> Vào màn hình list Thông báo (đi từ menu chính) --> Không hiển thị được danh sách (Test trên Postman thì thấy có data)

``` 
        {
            "_id": 570,
            "user_id": 2,
            "content": "Minh Hiếu vừa bình luận bài viết của bạn",
            "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5O_FDGvz81cKl8iCxYAv5nRR718sCXg--7ccAf8TNW6ASWKM1RA",
            "created_date": "2018-12-20T15:07:51.151Z"
        },
        {
            "_id": 573,
            "user_id": 2,
            "content": "Ngọc Như vừa bình luận bài viết của bạn",
            "image": "https://images.pexels.com/photos/462118/pexels-photo-462118.jpeg?auto=compress&cs=tinysrgb&h=350",
            "created_date": "2018-12-20T15:07:51.151Z"
        }
```
Dữ liệu trả về sai format nên client parse lỗi nha
